import argparse
import json
import os
import re
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple


@dataclass
class Node:
    id: str
    type: str  # "entity" or "relation"
    name: str
    desc: str
    text: str


@dataclass
class Edge:
    h_id: str
    r_id: str
    t_id: str
    split: str


def _tokenize(text: str) -> List[str]:
    """Very simple tokenizer: lowercase and keep alnum tokens."""
    return re.findall(r"[a-z0-9]+", text.lower())


class InternalGraphKB:
    """
    Lightweight in-memory KB for GraphRAG-style retrieval.

    - Loads nodes/edges from graph_kb/<dataset> generated by build_internal_kb.py
    - Provides simple lexical search over entity texts
    - Provides local subgraph expansion around one or more entities
    """

    def __init__(self, kb_root: Path):
        self.kb_root = kb_root
        self.nodes: Dict[str, Node] = {}
        self.entities: Dict[str, Node] = {}
        self.relations: Dict[str, Node] = {}

        self.edges: List[Edge] = []
        self.out_neighbors: Dict[str, List[Edge]] = defaultdict(list)
        self.in_neighbors: Dict[str, List[Edge]] = defaultdict(list)
        self.rel_neighbors: Dict[str, List[Edge]] = defaultdict(list)

        # simple lexical index over entity texts
        self.entity_tokens: Dict[str, Counter] = {}

        self._load()

    @classmethod
    def from_dataset(cls, dataset: str, kb_dir: str = "graph_kb") -> "InternalGraphKB":
        root = Path(__file__).resolve().parent.parent  # repo root
        kb_root = root / kb_dir / dataset
        return cls(kb_root)

    def _load(self) -> None:
        nodes_path = self.kb_root / "nodes.jsonl"
        edges_path = self.kb_root / "edges.jsonl"

        if not nodes_path.exists() or not edges_path.exists():
            raise FileNotFoundError(
                f"Expected nodes/edges at {nodes_path} and {edges_path}. "
                "Run rag_kge/build_internal_kb.py first."
            )

        # load nodes
        with nodes_path.open("r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                data = json.loads(line)
                node = Node(
                    id=str(data["id"]),
                    type=data["type"],
                    name=data.get("name", ""),
                    desc=data.get("desc", ""),
                    text=data.get("text", ""),
                )
                self.nodes[node.id] = node
                if node.type == "entity":
                    self.entities[node.id] = node
                elif node.type == "relation":
                    self.relations[node.id] = node

        # build lexical index for entities
        for ent_id, node in self.entities.items():
            tokens = _tokenize(node.text)
            self.entity_tokens[ent_id] = Counter(tokens)

        # load edges
        with edges_path.open("r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                data = json.loads(line)
                edge = Edge(
                    h_id=str(data["h_id"]),
                    r_id=str(data["r_id"]),
                    t_id=str(data["t_id"]),
                    split=data.get("split", "train"),
                )
                self.edges.append(edge)
                self.out_neighbors[edge.h_id].append(edge)
                self.in_neighbors[edge.t_id].append(edge)
                self.rel_neighbors[edge.r_id].append(edge)

    # ------------------------------------------------------------------
    # Simple lexical search over entity nodes
    # ------------------------------------------------------------------
    def search_entities(self, query: str, top_k: int = 5) -> List[Tuple[str, float]]:
        """
        Return top_k entity IDs with highest lexical overlap with the query.
        Score is |shared tokens| / |query tokens|.
        """
        q_tokens = _tokenize(query)
        if not q_tokens:
            return []
        q_set = Counter(q_tokens)

        scores: List[Tuple[str, float]] = []
        for ent_id, tok_counter in self.entity_tokens.items():
            # compute overlap count
            shared = sum((tok_counter & q_set).values())
            if shared == 0:
                continue
            score = shared / len(q_tokens)
            scores.append((ent_id, score))

        scores.sort(key=lambda x: x[1], reverse=True)
        return scores[:top_k]

    # ------------------------------------------------------------------
    # Local subgraph expansion
    # ------------------------------------------------------------------
    def get_local_subgraph(
        self,
        center_entities: Iterable[str],
        hops: int = 1,
        max_edges: int = 100,
        exclude_triples: Optional[Iterable[Tuple[str, str, str]]] = None,
    ) -> Tuple[List[Node], List[Edge]]:
        """
        Expand a local subgraph around the given entities.
        Returns the unique nodes and edges reached within the hop limit.
        """
        exclude_set = set()
        if exclude_triples is not None:
            for h, r, t in exclude_triples:
                exclude_set.add((h, r, t))

        visited_entities = set()
        frontier: List[Tuple[str, int]] = []
        for ent_id in center_entities:
            if ent_id in self.entities:
                visited_entities.add(ent_id)
                frontier.append((ent_id, 0))

        edges_set: List[Edge] = []
        nodes_set: Dict[str, Node] = {}

        while frontier and len(edges_set) < max_edges:
            current, depth = frontier.pop(0)
            nodes_set[current] = self.entities[current]

            if depth >= hops:
                continue

            # outgoing edges
            for e in self.out_neighbors.get(current, []):
                if (e.h_id, e.r_id, e.t_id) in exclude_set:
                    continue
                edges_set.append(e)
                # add relation and tail node
                if e.r_id in self.relations:
                    nodes_set[e.r_id] = self.relations[e.r_id]
                if e.t_id in self.entities and e.t_id not in visited_entities:
                    visited_entities.add(e.t_id)
                    frontier.append((e.t_id, depth + 1))
                    nodes_set[e.t_id] = self.entities[e.t_id]
                if len(edges_set) >= max_edges:
                    break

            if len(edges_set) >= max_edges:
                break

            # incoming edges
            for e in self.in_neighbors.get(current, []):
                if (e.h_id, e.r_id, e.t_id) in exclude_set:
                    continue
                edges_set.append(e)
                if e.r_id in self.relations:
                    nodes_set[e.r_id] = self.relations[e.r_id]
                if e.h_id in self.entities and e.h_id not in visited_entities:
                    visited_entities.add(e.h_id)
                    frontier.append((e.h_id, depth + 1))
                    nodes_set[e.h_id] = self.entities[e.h_id]
                if len(edges_set) >= max_edges:
                    break

        return list(nodes_set.values()), edges_set

    def get_alternative_triples(
        self,
        h_id: str,
        r_id: str,
        t_id: str,
        max_alternatives: int = 5,
        seed: int = 0,
    ) -> List[Tuple[str, str, str]]:
        """
        Build plausible alternative triples for contrastive prompting.

        Strategy:
        1) Same head+relation: (h, r, t_alt) where t_alt is observed in KG.
        2) Same relation+tail: (h_alt, r, t) where h_alt is observed in KG.
        3) Fallback: sample tails from other ( *, r, tail ) edges and plug into (h, r, tail).
        """
        import random

        rng = random.Random(seed)
        alts: List[Tuple[str, str, str]] = []
        seen = {(h_id, r_id, t_id)}

        # (h, r, ?)
        tails = [e.t_id for e in self.out_neighbors.get(h_id, []) if e.r_id == r_id]
        rng.shuffle(tails)
        for t2 in tails:
            cand = (h_id, r_id, t2)
            if cand in seen:
                continue
            alts.append(cand)
            seen.add(cand)
            if len(alts) >= max_alternatives:
                return alts

        # (?, r, t)
        heads = [e.h_id for e in self.in_neighbors.get(t_id, []) if e.r_id == r_id]
        rng.shuffle(heads)
        for h2 in heads:
            cand = (h2, r_id, t_id)
            if cand in seen:
                continue
            alts.append(cand)
            seen.add(cand)
            if len(alts) >= max_alternatives:
                return alts

        # fallback: sample tails from relation bucket
        pool = self.rel_neighbors.get(r_id, [])
        if pool:
            indices = list(range(len(pool)))
            rng.shuffle(indices)
            for i in indices:
                e = pool[i]
                cand = (h_id, r_id, e.t_id)
                if cand in seen:
                    continue
                alts.append(cand)
                seen.add(cand)
                if len(alts) >= max_alternatives:
                    break

        return alts

    def get_alternative_pool(
        self,
        h_id: str,
        r_id: str,
        t_id: str,
        max_pool: int = 50,
        seed: int = 0,
    ) -> List[Tuple[str, str, str]]:
        """
        Return a larger pool of plausible alternative triples for contrastive prompting.

        Pool includes (when available):
        - (h, r, t_alt) where (h, r, t_alt) is observed in KG
        - (h_alt, r, t) where (h_alt, r, t) is observed in KG

        This avoids fabricating unseen triples (keeps alternatives grounded in KG).
        """
        import random

        rng = random.Random(seed)
        seen = {(h_id, r_id, t_id)}
        pool: List[Tuple[str, str, str]] = []

        # observed tails for (h, r, ?)
        tails = [e.t_id for e in self.out_neighbors.get(h_id, []) if e.r_id == r_id]
        rng.shuffle(tails)
        for t2 in tails:
            cand = (h_id, r_id, t2)
            if cand in seen:
                continue
            pool.append(cand)
            seen.add(cand)
            if len(pool) >= max_pool:
                return pool

        # observed heads for (?, r, t)
        heads = [e.h_id for e in self.in_neighbors.get(t_id, []) if e.r_id == r_id]
        rng.shuffle(heads)
        for h2 in heads:
            cand = (h2, r_id, t_id)
            if cand in seen:
                continue
            pool.append(cand)
            seen.add(cand)
            if len(pool) >= max_pool:
                break

        return pool

    # ------------------------------------------------------------------
    # Rendering helpers
    # ------------------------------------------------------------------
    def format_triple(self, h_id: str, r_id: str, t_id: str) -> str:
        h_name = self.entities.get(h_id, Node(h_id, "entity", h_id, "", h_id)).name or h_id
        r_name = self.relations.get(r_id, Node(r_id, "relation", r_id, "", r_id)).name or r_id
        t_name = self.entities.get(t_id, Node(t_id, "entity", t_id, "", t_id)).name or t_id
        return f"({h_name}, {r_name}, {t_name})"

    def render_subgraph_as_text(
        self,
        h_id: str,
        r_id: str,
        t_id: str,
        hops: int = 1,
        max_edges: int = 50,
        include_descriptions: bool = True,
        exclude_candidate_from_neighborhood: bool = True,
    ) -> str:
        """
        Build a text description of the local graph around (h, r, t),
        suitable as context for an LLM.
        """
        center_entities = [h_id, t_id]
        exclude = [(h_id, r_id, t_id)] if exclude_candidate_from_neighborhood else None
        nodes, edges = self.get_local_subgraph(
            center_entities, hops=hops, max_edges=max_edges, exclude_triples=exclude
        )

        lines: List[str] = []

        # candidate triple
        lines.append("Candidate triple:")
        lines.append(self.format_triple(h_id, r_id, t_id))
        lines.append("")

        # entity descriptions
        if include_descriptions:
            for ent_id in center_entities:
                ent = self.entities.get(ent_id)
                if ent is None:
                    continue
                lines.append(f"Entity: {ent.name} (ID={ent.id})")
                if ent.desc:
                    lines.append(f"Description: {ent.desc}")
                lines.append("")

        # neighborhood triples
        lines.append("Graph neighborhood:")
        for idx, e in enumerate(edges, start=1):
            triple_str = self.format_triple(e.h_id, e.r_id, e.t_id)
            lines.append(f"{idx}. {triple_str}  [split={e.split}]")

        return "\n".join(lines)


# ----------------------------------------------------------------------
# Simple CLI for testing
# ----------------------------------------------------------------------

def parse_cli_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Demo: retrieve local graph context for a triple."
    )
    parser.add_argument(
        "--dataset",
        type=str,
        default="wn18rr",
        choices=["wn18rr", "fb15k-237", "nell995"],
        help="Dataset name under graph_kb/.",
    )
    parser.add_argument("--h_id", type=str, required=True, help="Head entity ID")
    parser.add_argument("--r_id", type=str, required=True, help="Relation ID")
    parser.add_argument("--t_id", type=str, required=True, help="Tail entity ID")
    parser.add_argument("--hops", type=int, default=1, help="Number of hops to expand")
    parser.add_argument(
        "--max_edges", type=int, default=50, help="Maximum number of edges in subgraph"
    )
    return parser.parse_args()


def main() -> None:
    args = parse_cli_args()
    kb = InternalGraphKB.from_dataset(args.dataset)
    text = kb.render_subgraph_as_text(
        h_id=args.h_id,
        r_id=args.r_id,
        t_id=args.t_id,
        hops=args.hops,
        max_edges=args.max_edges,
    )
    print(text)


if __name__ == "__main__":
    main()
