"""
Train a simple re-ranker for external documents / internal edges using
evidence-level labels generated by retrieval_labeler.py.

Features are lightweight (lexical overlap and structural cues) to avoid
heavy dependencies. The model uses scikit-learn's LogisticRegression if
available; otherwise falls back to a frequency baseline.

Usage (example):
python3 -m rag_kge.retrieval_scorer \
  --dataset wn18rr \
  --labels_path rag_kge/output/wn18rr/evidence_labels.jsonl \
  --output_model rag_kge/output/wn18rr/reranker_ext.pkl \
  --kind external
"""

import argparse
import json
import math
import pickle
from pathlib import Path
from typing import Dict, List, Tuple

from .internal_graphrag import InternalGraphKB
from .external_rag import ExternalTextKB


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Train a simple evidence re-ranker.")
    p.add_argument("--dataset", type=str, default="wn18rr", choices=["wn18rr", "fb15k-237", "nell995"])
    p.add_argument("--labels_path", type=str, required=True, help="Evidence labels JSONL from retrieval_labeler.")
    p.add_argument("--output_model", type=str, required=True, help="Path to save pickled model.")
    p.add_argument("--kind", type=str, default="external", choices=["external", "internal"], help="Which evidence type to train.")
    p.add_argument(
        "--pairwise",
        action="store_true",
        help="Train with pairwise samples (pos vs neg within the same triple) to mimic ranking.",
    )
    return p.parse_args()


def load_labels(path: Path, kind: str) -> List[Dict]:
    samples = []
    with path.open() as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            obj = json.loads(line)
            if obj.get("kind") != kind:
                continue
            samples.append(obj)
    return samples


def tokenize(text: str) -> List[str]:
    import re
    return re.findall(r"[a-z0-9]+", text.lower())


def build_features_external(
    kb_ext: ExternalTextKB, kb_int: InternalGraphKB, samples: List[Dict]
) -> Tuple[List[List[float]], List[int], List[str]]:
    X, y = [], []
    triples = []
    for obj in samples:
        doc = kb_ext.docs_by_id.get(obj["doc_id"])
        if doc is None:
            continue
        h_id = obj["triple"]["h_id"]
        r_id = obj["triple"]["r_id"]
        t_id = obj["triple"]["t_id"]
        y.append(int(obj["label"]))
        triples.append(f"{h_id}|{r_id}|{t_id}")

        h_node = kb_int.entities.get(h_id)
        t_node = kb_int.entities.get(t_id)
        r_node = kb_int.relations.get(r_id)
        h_name = h_node.name if h_node and h_node.name else h_id
        t_name = t_node.name if t_node and t_node.name else t_id
        r_name = r_node.name if r_node and r_node.name else r_id

        q_tokens = tokenize(f"{h_name} {r_name} {t_name}")
        d_tokens = tokenize(doc.text)
        overlap = len(set(q_tokens) & set(d_tokens))
        d_lower = doc.text.lower()
        contains_h = 1.0 if h_name and h_name.lower() in d_lower else 0.0
        contains_t = 1.0 if t_name and t_name.lower() in d_lower else 0.0
        length = len(doc.text)
        X.append([overlap, contains_h, contains_t, length])
    return X, y, triples


def build_features_internal(
    kb_int: InternalGraphKB, samples: List[Dict]
) -> Tuple[List[List[float]], List[int], List[str]]:
    X, y = [], []
    triples = []
    for obj in samples:
        edge = obj.get("edge") or {}
        h, r, t = edge.get("h_id"), edge.get("r_id"), edge.get("t_id")
        if not h or not r or not t:
            continue
        y.append(int(obj["label"]))
        triples.append(f"{obj['triple']['h_id']}|{obj['triple']['r_id']}|{obj['triple']['t_id']}")
        # simple structural cues
        same_head = 1.0 if h == obj["triple"]["h_id"] else 0.0
        same_tail = 1.0 if t == obj["triple"]["t_id"] else 0.0
        same_rel = 1.0 if r == obj["triple"]["r_id"] else 0.0
        deg_h = len(kb_int.out_neighbors.get(h, [])) + len(kb_int.in_neighbors.get(h, []))
        deg_t = len(kb_int.out_neighbors.get(t, [])) + len(kb_int.in_neighbors.get(t, []))
        X.append([same_head, same_tail, same_rel, deg_h, deg_t])
    return X, y, triples


def train_model(X: List[List[float]], y: List[int]) -> Dict:
    try:
        from sklearn.linear_model import LogisticRegression

        model = LogisticRegression(max_iter=200)
        model.fit(X, y)
        return {"type": "sklearn_logreg", "model": model}
    except Exception:
        # fallback: frequency baseline (prior)
        prior = sum(y) / len(y) if y else 0.5
        return {"type": "prior", "prior": prior}


def main() -> None:
    args = parse_args()
    labels = load_labels(Path(args.labels_path), args.kind)
    kb_int = InternalGraphKB.from_dataset(args.dataset)
    kb_ext = ExternalTextKB.from_dataset(args.dataset)

    if args.kind == "external":
        X_raw, y_raw, trip_ids = build_features_external(kb_ext, kb_int, labels)
    else:
        X_raw, y_raw, trip_ids = build_features_internal(kb_int, labels)

    if not X_raw:
        raise SystemExit("No samples to train on.")

    if args.pairwise:
        # build pairwise differences: pos vs neg within same triple group
        grouped: Dict[str, List[Tuple[List[float], int]]] = {}
        for feats, lab, tid in zip(X_raw, y_raw, trip_ids):
            grouped.setdefault(tid, []).append((feats, lab))
        X_pw, y_pw = [], []
        for feats in grouped.values():
            pos = [f for f, l in feats if l == 1]
            neg = [f for f, l in feats if l == 0]
            if not pos or not neg:
                continue
            for p in pos:
                for n in neg:
                    # feature diff (pos - neg), label=1 means pos > neg
                    diff = [a - b for a, b in zip(p, n)]
                    X_pw.append(diff)
                    y_pw.append(1)
                    # also add inverse pair
                    diff_inv = [b - a for a, b in zip(p, n)]
                    X_pw.append(diff_inv)
                    y_pw.append(0)
        if not X_pw:
            raise SystemExit("No pairwise samples to train on.")
        model = train_model(X_pw, y_pw)
        model["pairwise"] = True
    else:
        model = train_model(X_raw, y_raw)
        model["pairwise"] = False

    out_path = Path(args.output_model)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("wb") as f:
        pickle.dump(model, f)
    print(f"Saved model to {out_path}, samples={len(y_raw)}, positives={sum(y_raw)}, pairwise={model['pairwise']}")


if __name__ == "__main__":
    main()
